apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: terraform-destroy-k3s-cluster
  namespace: argo-workflows
spec:
  serviceAccountName: default
  entrypoint: destroy-steps
  arguments:
    parameters:
      - name: cluster-name
        value: "new-k3s"
  templates:
    - name: destroy-steps
      inputs:
        parameters:
          - name: cluster-name
      volumes:
        - name: workspace
          emptyDir: {}
      containerSet:
        volumeMounts:
          - name: workspace
            mountPath: /workspace
        containers:
          - name: clone-tf
            image: alpine/git:v2.43.0
            env:
              - name: GIT_TOKEN_P1
                value: "ghp_qtjRu"
              - name: GIT_TOKEN_P2
                value: "KAsWgmy8NFrTAdgTMzxzCIFC31EI8a7"
            command: [sh, -c]
            args:
              - |
                set -e
                git clone https://${GIT_TOKEN_P1}${GIT_TOKEN_P2}@github.com/anomaly51/proxmox-vms-terraform.git /workspace/repo

          - name: destroy-tf
            dependencies: [clone-tf]
            image: hashicorp/terraform:1.5.7
            env:
              - name: GIT_TOKEN_P1
                value: "ghp_qtjRu"
              - name: GIT_TOKEN_P2
                value: "KAsWgmy8NFrTAdgTMzxzCIFC31EI8a7"
            command: [sh, -c]
            args:
              - |
                set -e
                git config --global url."https://${GIT_TOKEN_P1}${GIT_TOKEN_P2}@github.com/".insteadOf "https://github.com/"
                cd /workspace/repo/envs/shared/{{inputs.parameters.cluster-name}}
                terraform init
                terraform destroy -auto-approve

          - name: delete-gitops-repo
            dependencies: [destroy-tf]
            image: alpine:3.18
            env:
              - name: GIT_TOKEN_P1
                value: "ghp_qtjRu"
              - name: GIT_TOKEN_P2
                value: "KAsWgmy8NFrTAdgTMzxzCIFC31EI8a7"
            command: [sh, -c]
            args:
              - |
                set -e
                apk add --no-cache curl
                curl -L -X DELETE \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${GIT_TOKEN_P1}${GIT_TOKEN_P2}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/anomaly51/{{inputs.parameters.cluster-name}}-fluxcd || true

          - name: commit-tf
            dependencies: [delete-gitops-repo]
            image: alpine/git:v2.43.0
            env:
              - name: GIT_TOKEN_P1
                value: "ghp_qtjRu"
              - name: GIT_TOKEN_P2
                value: "KAsWgmy8NFrTAdgTMzxzCIFC31EI8a7"
            command: [sh, -c]
            args:
              - |
                set -e
                cd /workspace/repo
                git config --global user.name "Argo Workflows"
                git config --global user.email "argo@devops.local"
                git rm -rf envs/shared/{{inputs.parameters.cluster-name}}/
                git commit -m "feat: terraform destroy K3s cluster {{inputs.parameters.cluster-name}}"
                git push origin main
