apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nfs-provisioner
  - minio
  - cnpg-system
  - shisha-guid
  - cert-manager
  - external-dns
  - cloudflared
  - external-secrets
