apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "e973f7606cb88053c7fc59774140f273",
      "TunnelSecret": "ZsPqDWH4JWariK/+jh7qHM3PUGh+NPbPSD+nXv38xK0=",
      "TunnelID": "7782dfed-9ebb-4c58-b21f-30020b7c80ef"
    }
